# Use the official Kibana image as base (version must match Elasticsearch)
FROM kibana:8.15.3

# Set environment variables to configure Kibana
# Disable Fleet agents (simplifies the setup in development environments)
ENV xpack.fleet.agents.enabled=false
    # SERVER_SSL_ENABLED=false \
    # XPACK_SECURITY_ENABLED="true" \
    
    

